# Default editor and pager
EDITOR=vim
VISUAL=vim
PAGER=bat
MANPAGER=bat
SYSTEMD_PAGER=bat
GIT_PAGER=bat

# User PATH additions
PATH=${PATH}:${HOME}/.cargo/bin:${HOME}/.npm-global/bin:${HOME}/.scripts:${HOME}/.local/bin

# Node.js
NODE_OPTIONS=--localstorage-file=/tmp/node-localstorage.json

# Kubernetes
KUBECONFIG=${HOME}/.kube/config-hostinger
